# Generated by Django 4.1.7 on 2023-08-14 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Property', '0002_alter_propertysubtypes_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=250)),
                ('name_ar', models.CharField(blank=True, max_length=250, null=True)),
                ('writer_en', models.CharField(max_length=250)),
                ('writer_ar', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='')),
                ('related_properties', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Property.general')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='BlogDescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.TextField(max_length=500)),
                ('name_ar', models.TextField(blank=True, max_length=500, null=True)),
                ('description_en', models.TextField(max_length=500)),
                ('description_ar', models.TextField(blank=True, max_length=500, null=True)),
                ('order', models.PositiveIntegerField()),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogs.blog')),
            ],
            options={
                'verbose_name': 'Blog Descriptions',
                'verbose_name_plural': 'Blog Descriptions',
            },
        ),
    ]
