# Generated by Django 4.1.7 on 2023-08-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogdescriptions',
            old_name='description_ar',
            new_name='list_items_ar',
        ),
        migrations.RenameField(
            model_name='blogdescriptions',
            old_name='description_en',
            new_name='list_items_en',
        ),
        migrations.RenameField(
            model_name='blogdescriptions',
            old_name='name_ar',
            new_name='paragraph_ar',
        ),
        migrations.RenameField(
            model_name='blogdescriptions',
            old_name='name_en',
            new_name='paragraph_en',
        ),
    ]
