# Generated by Django 4.1.7 on 2023-08-11 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=250)),
                ('title_ar', models.CharField(blank=True, max_length=250, null=True)),
                ('description_en', models.TextField(max_length=500)),
                ('description_ar', models.TextField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(max_length=250)),
                ('phone_icon', models.ImageField(upload_to='documents/')),
                ('email', models.EmailField(max_length=254)),
                ('email_icon', models.ImageField(upload_to='documents/')),
                ('link', models.URLField()),
                ('location_en', models.CharField(max_length=250)),
                ('location_ar', models.CharField(blank=True, max_length=250, null=True)),
                ('location_icon', models.ImageField(upload_to='documents/')),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='ZoomForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=15)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('contact_us', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contactus.contactus')),
            ],
            options={
                'verbose_name': 'Zoom Form',
                'verbose_name_plural': 'Zoom Form',
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=15)),
                ('subject', models.TextField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=500)),
                ('contact_us', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contactus.contactus')),
            ],
            options={
                'verbose_name': 'Contact Form',
                'verbose_name_plural': 'Contact Form',
            },
        ),
    ]
