# Generated by Django 4.1.7 on 2023-08-08 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_we_provide_title_en', models.CharField(max_length=250)),
                ('what_we_provide_title_ar', models.CharField(blank=True, max_length=250, null=True)),
                ('contact_title_en', models.CharField(max_length=250)),
                ('contact_title_ar', models.CharField(blank=True, max_length=250, null=True)),
                ('contact_description_en', models.TextField(max_length=500)),
                ('contact_description_ar', models.TextField(blank=True, max_length=500, null=True)),
                ('contact_image', models.ImageField(upload_to='')),
                ('contact_background', models.ImageField(upload_to='')),
                ('recommend_properties_title_en', models.CharField(max_length=250)),
                ('recommend_properties_title_ar', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'General',
            },
        ),
        migrations.CreateModel(
            name='WhatWeProvides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='documents/')),
                ('name_en', models.CharField(max_length=250)),
                ('name_ar', models.CharField(blank=True, max_length=250, null=True)),
                ('description_en', models.TextField(max_length=500)),
                ('description_ar', models.TextField(blank=True, max_length=500, null=True)),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.home')),
            ],
            options={
                'verbose_name': 'What We Provides',
                'verbose_name_plural': 'What We Provides',
            },
        ),
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video_or_image', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.home')),
            ],
            options={
                'verbose_name': 'Home Slider',
                'verbose_name_plural': 'Home Slider',
            },
        ),
    ]
