# Generated by Django 4.1.7 on 2023-08-11 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'General', 'verbose_name_plural': 'Home'},
        ),
    ]
