# Generated by Django 4.1.7 on 2023-08-13 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertysubtypes',
            options={'verbose_name': 'Property Sub Types', 'verbose_name_plural': 'Property Sub Types'},
        ),
        migrations.AlterModelOptions(
            name='propertytypes',
            options={'verbose_name': 'Property Types', 'verbose_name_plural': 'Property Types'},
        ),
    ]
